### PR TITLE
Add missing titles and descriptions to regos that were missing them

### PR DESCRIPTION
**Pull request by louislang**

### CODE REVIEW

**Comment by matt-phylum** [comment]
I thought we deleted these three policies?

**Comment by louislang** [comment]
If we did, we should delete this and remove from prod. But when I first pulled this repo and uploaded using this script, they were present in the clone.

**Comment by matt-phylum** [comment]
`default.rego` isn't the default anymore. It's been replaced by the new default set.

I think `license_agpl.rego` has been replaced by `copyleft_license.rego`. `copyleft_license` is more general and uses an issue tag instead of looking at the license string with regular expressions.

`per_domain.rego` was more of an example of how to write a custom policy than a policy that we could recommend to users via the policy store. It's hard to explain what it does or why you would want a reusable policy that does specifically that, especially now that we support combining policies.

It looks like they're still in the repo, so we could use this PR to remove them.

**Comment by furi0us333** [comment]
@matt-phylum is correct. I am closing this PR in favor or removing them via https://github.com/phylum-dev/policy/pull/12

**Pull request closed without merging**
